### ISSUE TITLE
Application Plank-adp fails to launch

### ISSUE THREAD

**Issue by rdlf4** [matricci/plank-adp#1]
I'm on Cinnamon, running Linux Mint 19.1 Tessa 64-bit
As per your project description, it seems Cinnamon is now supported. So I went further with it to see how it goes.
At first, installer.sh runs a check and determines Python pip and Dconf-tools are installed. Then, it goes after Pillow (Python Image Library) by itself (you provided the dependency _Python Pillow_ with a space, so I can't figure that out. Perhaps you're referring to _python-pil_?) Anyways, it finds and installs Pillow 6.1.0. And then this happens:
```
 Collecting Pillow
  Using cached https://files.pythonhosted.org/packages/cc/a4/79b5f36d1e1a2b426073bd62217d1530fcd939950c2936651e6b39127a9b/Pillow-6.1.0-cp27-cp27mu-manylinux1_x86_64.whl
Installing collected packages: Pillow
Successfully installed Pillow-6.1.0
Collecting pycairo
  Using cached https://files.pythonhosted.org/packages/48/20/5e83af98eb897935bf7dc39455e892ba866feebb9b7c3b392982866f9958/pycairo-1.18.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
ImportError:  No module named setuptools
```

The same goes for PyGobject, it collects, then setup.py triggers the same ImportError error message. Because of that, I guess PyGobject isn't installed, which triggers the following:
_Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-JovOND/PyGobject/_

As a result, plank-adp won't show up.
Have you tried plank-adp on Linux Mint Cinnamon? If so, does it work out of the box for you?

**Comment by rdlf4** [comment]
Update: Managed to install setuptools with:
` pip install -U pip setuptools
`
After that, I was able to follow the instructions and get your application running.
But the end result is not blur. Matter of fact, it doesn't even resemble it. A blur effect is just like a transparent image with a foggy look to it. Instead what I get is a dark image with no transparency at all, as you can see from this screenshot.
![bs](https://user-images.githubusercontent.com/17544190/65595127-0e3a4680-df62-11e9-8cf7-b8e538eed224.png)
But instead, this is what is expected:
![yw](https://user-images.githubusercontent.com/17544190/65595230-45a8f300-df62-11e9-9aba-b27df1ee376f.png)
Initially I thought it could be something that went wrong with my setup, but after looking at the picture that you provided, my results are exactly just like yours. In other words, this is not blur effect.

**Comment by matricci** [comment]
Hey there! the script is a real blur, it just crops your wallpaper roughly where the dock cover, then get the average color, by resizing to 1x1 pixels, and generate the dock theme.
By the time that I started to code this project, I had a garbage notebook, and I couldn't run blur, so I hack it and call it a day, it really does not resemble a proper blur effect, it's just a thing that I think that makes a pretty effect on some images. Thank you for the feedback man!

**Comment by matricci** [comment]
The pip error does occur sometimes, but I don't know if that is caused by some dependencies, I tested it on elementaryOS 5.1 now, it works just fine. 
I will put your Issue on the `README` with the fix!
